/* tslint:disable */
/* eslint-disable */
/**
 * Practice API Documentation
 * Practice API description
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@admin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatedUser
 */
export interface CreatedUser {
    /**
     * ID of the user
     * @type {any}
     * @memberof CreatedUser
     */
    id?: any | null;
    /**
     * Name of the user
     * @type {any}
     * @memberof CreatedUser
     */
    name?: any | null;
    /**
     * Email of the user
     * @type {any}
     * @memberof CreatedUser
     */
    email?: any | null;
    /**
     * Email verification
     * @type {any}
     * @memberof CreatedUser
     */
    emailVerifiedAt?: any | null;
    /**
     * Password of the user
     * @type {any}
     * @memberof CreatedUser
     */
    password?: any | null;
    /**
     * Creation date
     * @type {Date}
     * @memberof CreatedUser
     */
    createdAt?: Date;
    /**
     * Last update date
     * @type {Date}
     * @memberof CreatedUser
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the CreatedUser interface.
 */
export function instanceOfCreatedUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreatedUserFromJSON(json: any): CreatedUser {
    return CreatedUserFromJSONTyped(json, false);
}

export function CreatedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'emailVerifiedAt': !exists(json, 'email_verified_at') ? undefined : json['email_verified_at'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function CreatedUserToJSON(value?: CreatedUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'email_verified_at': value.emailVerifiedAt,
        'password': value.password,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

