/* tslint:disable */
/* eslint-disable */
/**
 * Practice API Documentation
 * Practice API description
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@admin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatedAndUpdatedDates
 */
export interface CreatedAndUpdatedDates {
    /**
     * Creation date
     * @type {Date}
     * @memberof CreatedAndUpdatedDates
     */
    createdAt?: Date;
    /**
     * Last update date
     * @type {Date}
     * @memberof CreatedAndUpdatedDates
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the CreatedAndUpdatedDates interface.
 */
export function instanceOfCreatedAndUpdatedDates(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreatedAndUpdatedDatesFromJSON(json: any): CreatedAndUpdatedDates {
    return CreatedAndUpdatedDatesFromJSONTyped(json, false);
}

export function CreatedAndUpdatedDatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedAndUpdatedDates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function CreatedAndUpdatedDatesToJSON(value?: CreatedAndUpdatedDates | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

