/* tslint:disable */
/* eslint-disable */
/**
 * Practice API Documentation
 * Practice API description
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@admin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationLinksInner
 */
export interface PaginationLinksInner {
    /**
     * 
     * @type {string}
     * @memberof PaginationLinksInner
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginationLinksInner
     */
    label?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationLinksInner
     */
    active?: boolean;
}

/**
 * Check if a given object implements the PaginationLinksInner interface.
 */
export function instanceOfPaginationLinksInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginationLinksInnerFromJSON(json: any): PaginationLinksInner {
    return PaginationLinksInnerFromJSONTyped(json, false);
}

export function PaginationLinksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationLinksInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'active': !exists(json, 'active') ? undefined : json['active'],
    };
}

export function PaginationLinksInnerToJSON(value?: PaginationLinksInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'label': value.label,
        'active': value.active,
    };
}

