/* tslint:disable */
/* eslint-disable */
/**
 * Practice API Documentation
 * Practice API description
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@admin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationLinksInner } from './PaginationLinksInner';
import {
    PaginationLinksInnerFromJSON,
    PaginationLinksInnerFromJSONTyped,
    PaginationLinksInnerToJSON,
} from './PaginationLinksInner';
import type { User1Inner } from './User1Inner';
import {
    User1InnerFromJSON,
    User1InnerFromJSONTyped,
    User1InnerToJSON,
} from './User1Inner';

/**
 * 
 * @export
 * @interface PaginatedUser
 */
export interface PaginatedUser {
    /**
     * 
     * @type {number}
     * @memberof PaginatedUser
     */
    currentPage?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedUser
     */
    firstPageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof PaginatedUser
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedUser
     */
    lastPage?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedUser
     */
    lastPageUrl?: string;
    /**
     * 
     * @type {Array<PaginationLinksInner>}
     * @memberof PaginatedUser
     */
    links?: Array<PaginationLinksInner>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedUser
     */
    nextPageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedUser
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof PaginatedUser
     */
    perPage?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedUser
     */
    prevPageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaginatedUser
     */
    to?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedUser
     */
    total?: number;
    /**
     * 
     * @type {Array<User1Inner>}
     * @memberof PaginatedUser
     */
    data?: Array<User1Inner>;
}

/**
 * Check if a given object implements the PaginatedUser interface.
 */
export function instanceOfPaginatedUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedUserFromJSON(json: any): PaginatedUser {
    return PaginatedUserFromJSONTyped(json, false);
}

export function PaginatedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentPage': !exists(json, 'current_page') ? undefined : json['current_page'],
        'firstPageUrl': !exists(json, 'first_page_url') ? undefined : json['first_page_url'],
        'from': !exists(json, 'from') ? undefined : json['from'],
        'lastPage': !exists(json, 'last_page') ? undefined : json['last_page'],
        'lastPageUrl': !exists(json, 'last_page_url') ? undefined : json['last_page_url'],
        'links': !exists(json, 'links') ? undefined : ((json['links'] as Array<any>).map(PaginationLinksInnerFromJSON)),
        'nextPageUrl': !exists(json, 'next_page_url') ? undefined : json['next_page_url'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'perPage': !exists(json, 'per_page') ? undefined : json['per_page'],
        'prevPageUrl': !exists(json, 'prev_page_url') ? undefined : json['prev_page_url'],
        'to': !exists(json, 'to') ? undefined : json['to'],
        'total': !exists(json, 'total') ? undefined : json['total'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(User1InnerFromJSON)),
    };
}

export function PaginatedUserToJSON(value?: PaginatedUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current_page': value.currentPage,
        'first_page_url': value.firstPageUrl,
        'from': value.from,
        'last_page': value.lastPage,
        'last_page_url': value.lastPageUrl,
        'links': value.links === undefined ? undefined : ((value.links as Array<any>).map(PaginationLinksInnerToJSON)),
        'next_page_url': value.nextPageUrl,
        'path': value.path,
        'per_page': value.perPage,
        'prev_page_url': value.prevPageUrl,
        'to': value.to,
        'total': value.total,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(User1InnerToJSON)),
    };
}

